<a href="https://colab.research.google.com/github/TahaBerk58/learning-area/blob/main/R%20Tutorial/Fundamentals_of_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# R Operators

### Arithmetic Operations in R
- **Vector Definitions**: `vec1` and `vec2` are numeric vectors defined for performing arithmetic operations.
- **Addition**: Adds the corresponding elements of two vectors using the `+` operator.
- **Subtraction**: Subtracts the elements of the second vector from the first vector using the `-` operator.
- **Multiplication**: Multiplies the corresponding elements of two vectors using the `*` operator.
- **Division**: Divides the elements of the first vector by the corresponding elements of the second vector using the `/` operator.
- **Modulo**: Computes the remainder of division for each pair of elements using the `%%` operator.
- **Power Operator**: Raises the elements of the first vector to the power of the corresponding elements in the second vector using the `^` operator.
- **Output**: Results of the operations are displayed using the `cat()` function for clear formatting and separation.

In [32]:
# R program to illustrate
# the use of Arithmetic operators
vec1 <- c(0, 2)
vec2 <- c(2, 3)

# Performing operations on Operands
cat ("Addition of vectors :", vec1 + vec2, "\n")
cat ("Subtraction of vectors :", vec1 - vec2, "\n")
cat ("Multiplication of vectors :", vec1 * vec2, "\n")
cat ("Division of vectors :", vec1 / vec2, "\n")
cat ("Modulo of vectors :", vec1 %% vec2, "\n")
cat ("Power operator :", vec1 ^ vec2)

Addition of vectors : 2 5 
Subtraction of vectors : -2 -1 
Multiplication of vectors : 0 6 
Division of vectors : 0 0.6666667 
Modulo of vectors : 0 2 
Power operator : 0 8

### Element-wise Logical OR Operator (`|`) in R
- **Operation**: The `|` operator performs an element-wise logical OR operation between two vectors. It returns `TRUE` if either of the corresponding elements in the two vectors is `TRUE`, and `FALSE` otherwise.
- **Vectors**:
  - `list1 <- c(TRUE, 0.1)` defines a logical vector, where `TRUE` and `0.1` are interpreted as `TRUE` and `TRUE` respectively (non-zero numbers are considered `TRUE` in logical operations).
  - `list2 <- c(0, 4+3i)` defines a vector where `0` is considered `FALSE` and any non-zero complex number (`4+3i`) is considered `TRUE`.
- **Output**: The result of the logical OR operation is a logical vector indicating whether each pair of corresponding elements in `list1` and `list2` evaluates to `TRUE` or not.

The code will output the result of the logical OR between the two vectors element by element.

In [33]:
# Element-wise Logical OR operator (|)
# Returns True if either of the operands is True.
list1 <- c(TRUE, 0.1)
list2 <- c(0,4+3i)
print(list1|list2)

[1] TRUE TRUE


### Logical Operators in R
- **Vector Definitions**:
  - `vec1 <- c(0,2)` defines a numeric vector.
  - `vec2 <- c(TRUE,FALSE)` defines a logical vector.

- **Element-wise AND (`&`)**: The `&` operator performs a logical AND operation element by element between two vectors. It returns `TRUE` if both elements are `TRUE`, and `FALSE` otherwise.
  
- **Element-wise OR (`|`)**: The `|` operator performs a logical OR operation element by element between two vectors. It returns `TRUE` if at least one element is `TRUE`, and `FALSE` if both are `FALSE`.

- **Logical AND (`&&`)**: The `&&` operator evaluates only the first element of each vector and returns `TRUE` if both are `TRUE`, otherwise `FALSE`. It performs the logical AND operation for single elements, not vectors.

- **Logical OR (`||`)**: The `||` operator evaluates only the first element of each vector and returns `TRUE` if at least one of the elements is `TRUE`, otherwise `FALSE`. Like the logical AND, it operates on single elements.

- **Negation (`!`)**: The `!` operator inverts the logical values in `vec1`. `TRUE` becomes `FALSE`, and `FALSE` becomes `TRUE`.

- **Output**: Each operation's result is displayed using the `cat()` function to show the logical results clearly.

In [34]:
# R program to illustrate
# the use of Logical operators
vec1 <- c(0,2)
vec2 <- c(TRUE,FALSE)

# Performing operations on Operands
cat ("Element wise AND :", vec1 & vec2, "\n")
cat ("Element wise OR :", vec1 | vec2, "\n")
cat ("Logical AND :", vec1[1] && vec2[1], "\n")
cat ("Logical OR :", vec1[1] || vec2[1], "\n")
cat ("Negation :", !vec1)

Element wise AND : FALSE FALSE 
Element wise OR : TRUE TRUE 
Logical AND : FALSE 
Logical OR : TRUE 
Negation : TRUE FALSE

### Relational Operators in R
- **Vector Definitions**:
  - `vec1 <- c(0, 2)` defines a numeric vector with two elements: 0 and 2.
  - `vec2 <- c(2, 3)` defines another numeric vector with two elements: 2 and 3.

- **Relational Operations**:
  - **Less than (`<`)**: Compares corresponding elements in `vec1` and `vec2`. It returns `TRUE` if an element in `vec1` is less than the corresponding element in `vec2`, otherwise `FALSE`.
  - **Less than or equal to (`<=`)**: Compares the corresponding elements and returns `TRUE` if an element in `vec1` is less than or equal to the corresponding element in `vec2`.
  - **Greater than (`>`)**: Compares the corresponding elements and returns `TRUE` if an element in `vec1` is greater than the corresponding element in `vec2`.
  - **Greater than or equal to (`>=`)**: Compares the corresponding elements and returns `TRUE` if an element in `vec1` is greater than or equal to the corresponding element in `vec2`.
  - **Not equal to (`!=`)**: Compares the corresponding elements and returns `TRUE` if an element in `vec1` is not equal to the corresponding element in `vec2`.

- **Output**: Each relational operation is performed and displayed using the `cat()` function to show the results clearly.

In [35]:
# R program to illustrate
# the use of Relational operators
vec1 <- c(0, 2)
vec2 <- c(2, 3)

# Performing operations on Operands
cat ("Vector1 less than Vector2 :", vec1 < vec2, "\n")
cat ("Vector1 less than equal to Vector2 :", vec1 <= vec2, "\n")
cat ("Vector1 greater than Vector2 :", vec1 > vec2, "\n")
cat ("Vector1 greater than equal to Vector2 :", vec1 >= vec2, "\n")
cat ("Vector1 not equal to Vector2 :", vec1 != vec2, "\n")

Vector1 less than Vector2 : TRUE TRUE 
Vector1 less than equal to Vector2 : TRUE TRUE 
Vector1 greater than Vector2 : FALSE FALSE 
Vector1 greater than equal to Vector2 : FALSE FALSE 
Vector1 not equal to Vector2 : TRUE TRUE 


### Assignment Operators in R

- **Assignment Operators**:
  - **`<-`**: This is the most common assignment operator in R. It assigns the values on the right side to the variable on the left side. For example, `vec1 <- c(2:5)` assigns the vector `c(2, 3, 4, 5)` to `vec1`.
  
  - **`->`**: This operator is the reverse of `<-`, meaning the value on the left is assigned to the variable on the right. For example, `c(2:5) -> vec2` assigns the vector `c(2, 3, 4, 5)` to `vec2`.

  - **`<<-`**: This operator assigns a value to a variable in the global environment, even if the variable exists in a local scope (inside a function, for example). For instance, `vec3 <<- c(2:5)` assigns the vector `c(2, 3, 4, 5)` to `vec3` in the global environment.

  - **`=`**: This is another assignment operator, which works similarly to `<-`. For example, `vec4 = c(2:5)` assigns the vector `c(2, 3, 4, 5)` to `vec4`.

  - **`->>`**: This operator is a variant of `<<-`, used for assigning values globally in a more explicit manner. For example, `c(2:5) ->> vec5` assigns the vector `c(2, 3, 4, 5)` to `vec5` in the global environment.

- **Output**:
  - The program prints each vector using `cat()` to display the values stored in `vec1`, `vec2`, `vec3`, `vec4`, and `vec5`.


In [36]:
# R program to illustrate
# the use of Assignment operators
vec1 <- c(2:5)
c(2:5) ->> vec2
vec3 <<- c(2:5)
vec4 = c(2:5)
c(2:5) -> vec5

# Performing operations on Operands
cat ("vector 1 :", vec1, "\n")
cat("vector 2 :", vec2, "\n")
cat ("vector 3 :", vec3, "\n")
cat("vector 4 :", vec4, "\n")
cat("vector 5 :", vec5)

vector 1 : 2 3 4 5 
vector 2 : 2 3 4 5 
vector 3 : 2 3 4 5 
vector 4 : 2 3 4 5 
vector 5 : 2 3 4 5

In [37]:
val <- 0.1
 list1 <- c(TRUE, 0.1,"apple")
 print (val %in% list1)

[1] TRUE


In [38]:
mat = matrix(c(1,2,3,4,5,6),nrow=2,ncol=3)
         print (mat)
         print( t(mat))
         pro = mat %*% t(mat)
         print(pro)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
     [,1] [,2]
[1,]   35   44
[2,]   44   56


In [39]:
# R program to illustrate
# the use of Miscellaneous operators
mat <- matrix (1:4, nrow = 1, ncol = 4)
print("Matrix elements using : ")
print(mat)

product = mat %*% t(mat)
print("Product of matrices")
print(product,)
cat ("does 1 exist in prod matrix :", "1" %in% product)

[1] "Matrix elements using : "
     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[1] "Product of matrices"
     [,1]
[1,]   30
does 1 exist in prod matrix : FALSE

## Keywords

In [40]:
x <- 5

# Check value is less than or greater than 10
if(x > 10)
{
	print(paste(x, "is greater than 10"))
} else
{
	print(paste(x, "is less than 10"))
}


[1] "5 is less than 10"


In [41]:
# R program to demonstrate the use of while loop

val = 1

# using while loop
while (val <= 5 )
{
	# statements
	print(val)
	val = val + 1
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [42]:
# R program to demonstrate the use of repeat loop

val = 1

# using repeat loop
repeat
{
	# statements
	print(val)
	val = val + 1

	# checking stop condition
	if(val > 5)
	{
		# using break statement
		# to terminate the loop
		break
	}
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [43]:
# R program to demonstrate the use of for loop

# using for loop
for (val in 1:5)
{
	# statement
	print(val)
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [44]:
# A simple R function to check
# whether x is even or odd

evenOdd = function(x){
if(x %% 2 == 0)
	return("even")
else
	return("odd")
}

print(evenOdd(4))
print(evenOdd(3))


[1] "even"
[1] "odd"


In [45]:
# R program to illustrate next in for loop

val <- 6:11

# Loop
for (i in val)
{
	if (i == 8)
	{
		# test expression
		next
	}
	print(i)
}


[1] 6
[1] 7
[1] 9
[1] 10
[1] 11


In [46]:
# R Break Statement Example
a<-1
while (a < 10)
{
	print(a)
	if(a == 5)
		break
	a = a + 1
}


[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [47]:
# A simple R program
# to illustrate NULL

v = as.null(c(1, 2, 3, 4))
print(v)

NULL


In [48]:
# A simple R program
# to illustrate Inf and NaN

# To check Inf
x = c(Inf, 2, 3)
print(is.finite(x))

# To check NaN
y = c(1, NaN, 3)
print(is.nan(y))

[1] FALSE  TRUE  TRUE
[1] FALSE  TRUE FALSE


## Data Types

In [49]:
# A simple R program
# to illustrate Numeric data type

# Assign a decimal value to x
x = 5.6

# print the class name of variable
print(class(x))

# print the type of variable
print(typeof(x))

[1] "numeric"
[1] "double"


In [50]:
# A simple R program
# to illustrate Numeric data type

# Assign a integer value to y
y = 5

# is y an integer?
print(is.integer(y))

[1] FALSE


In [51]:
# A simple R program
# to illustrate integer data type

# Create an integer value
x = as.integer(5)

# print the class name of x
print(class(x))

# print the type of x
print(typeof(x))

# Declare an integer by appending an L suffix.
y = 5L

# print the class name of y
print(class(y))

# print the type of y
print(typeof(y))

[1] "integer"
[1] "integer"
[1] "integer"
[1] "integer"


In [52]:
# A simple R program
# to illustrate logical data type

# Sample values
x = 4
y = 3

# Comparing two values
z = x > y

# print the logical value
print(z)

# print the class name of z
print(class(z))

# print the type of z
print(typeof(z))

[1] TRUE
[1] "logical"
[1] "logical"


In [53]:
# A simple R program
# to illustrate complex data type

# Assign a complex value to x
x = 4 + 3i

# print the class name of x
print(class(x))

# print the type of x
print(typeof(x))

[1] "complex"
[1] "complex"


In [54]:
# A simple R program
# to illustrate character data type

# Assign a character value to char
char = "Geeksforgeeks"

# print the class name of char
print(class(char))

# print the type of char
print(typeof(char))

[1] "character"
[1] "character"


In [55]:
# Create a raw vector
x <- as.raw(c(0x1, 0x2, 0x3, 0x4, 0x5))
print(x)

[1] 01 02 03 04 05


In [56]:
# A simple R program
# to find data type of an object

# Logical
print(class(TRUE))

# Integer
print(class(3L))

# Numeric
print(class(10.5))

# Complex
print(class(1+2i))

# Character
print(class("12-04-2020"))

[1] "logical"
[1] "integer"
[1] "numeric"
[1] "complex"
[1] "character"


In [57]:
# A simple R program
# Verify if an object is of a certain datatype

# Logical
print(is.logical(TRUE))

# Integer
print(is.integer(3L))

# Numeric
print(is.numeric(10.5))

# Complex
print(is.complex(1+2i))

# Character
print(is.character("12-04-2020"))

print(is.integer("a"))

print(is.numeric(2+3i))

[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
[1] TRUE
[1] FALSE
[1] FALSE


In [58]:
# A simple R program
# convert data type of an object to another

# Logical
print(as.numeric(TRUE))

# Integer
print(as.complex(3L))

# Numeric
print(as.logical(10.5))

# Complex
print(as.character(1+2i))

# Can't possible
print(as.numeric("12-04-2020"))

[1] 1
[1] 3+0i
[1] TRUE
[1] "1+2i"


Warning message in print(as.numeric("12-04-2020")):
“NAs introduced by coercion”


[1] NA
